# https://postgrest.org/en/stable/install.html#containerized-postgrest-and-db-with-docker-compose
version: '3'
volumes:
  pgdata:
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ssot
      POSTGRES_USER: workbc
      POSTGRES_PASSWORD: workbc
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - "./postgres-init:/docker-entrypoint-initdb.d"
  ssot:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://workbc:workbc@postgres:5432/ssot
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: ssot_readonly
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
    depends_on:
      - postgres
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:3000/
    depends_on:
      - ssot
  migrator:
    build:
      context: ./migration
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    volumes:
      - ./migration:/app
    environment:
      PGUSER: workbc
      PGPASSWORD: workbc
      PGDATABASE: ssot
      PGHOST: postgres
